[package]
name = "multi_tree"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
igui_backend_recording = { workspace = true }
igui_components = { workspace = true }
igui_core = { workspace = true }
igui_render = { workspace = true }
igui_scene = { workspace = true }
igui_theme = { workspace = true }
igui_ui = { workspace = true }
