[package]
name = "multi_tree"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cobbled_backend_recording = { workspace = true }
cobbled_components = { workspace = true }
cobbled_core = { workspace = true }
cobbled_render = { workspace = true }
cobbled_scene = { workspace = true }
cobbled_theme = { workspace = true }
cobbled_ui = { workspace = true }
