[package]
name = "game_demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
igui_core.workspace = true
igui_render.workspace = true
igui_scene.workspace = true
igui_ui.workspace = true
igui_theme.workspace = true
igui_components.workspace = true
igui_anim.workspace = true
igui_assets.workspace = true
igui_game.workspace = true
igui_backend_wgpu.workspace = true
igui_backend_recording.workspace = true
winit = "0.30"
