[package]
name = "game_demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rough_core.workspace = true
rough_render.workspace = true
rough_scene.workspace = true
rough_ui.workspace = true
rough_theme.workspace = true
rough_components.workspace = true
rough_anim.workspace = true
rough_assets.workspace = true
rough_game = { workspace = true, features = ["ui"] }
rough_backend_wgpu.workspace = true
rough_backend_recording.workspace = true
winit = "0.30"
