[package]
name = "game_demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
cobbled_core.workspace = true
cobbled_render.workspace = true
cobbled_scene.workspace = true
cobbled_ui.workspace = true
cobbled_theme.workspace = true
cobbled_components.workspace = true
cobbled_anim.workspace = true
cobbled_assets.workspace = true
cobbled_game = { workspace = true, features = ["ui"] }
cobbled_backend_wgpu.workspace = true
cobbled_backend_recording.workspace = true
winit = "0.30"
