[package]
name = "web_demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
igui_core.workspace = true
igui_render.workspace = true
igui_scene.workspace = true
igui_ui.workspace = true
igui_wasm.workspace = true
demo_app.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "HtmlElement", "CanvasRenderingContext2d"] }
