[package]
name = "igui_game"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
igui_core.workspace = true
igui_render.workspace = true
igui_scene.workspace = true
igui_assets.workspace = true
igui_anim.workspace = true

[dev-dependencies]
igui_backend_recording.workspace = true
