[package]
name = "rough_debug_ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rough_core.workspace = true
rough_scene.workspace = true
rough_render.workspace = true
rough_ui.workspace = true
rough_components.workspace = true
rough_profile.workspace = true
