[package]
name = "cobbled_debug_ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cobbled_core.workspace = true
cobbled_scene.workspace = true
cobbled_render.workspace = true
cobbled_ui.workspace = true
cobbled_components.workspace = true
cobbled_profile.workspace = true
